name: "Continuous Integration"

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5
          cache: false
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check
        run: make check
      - name: Secure dockerfile
        run: make dockerfile-security
